[build]
  command = "ng build --configuration production"
  publish = "dist/angular-new-features"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  external_node_modules = ["@netlify/angular-runtime"]